#!/bin/bash

echo "🚀 I-TO-SAI Deployment Helper"
echo "================================"

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. ✅ GitHub repository with your code"
echo "2. ✅ Vercel account (sign up at vercel.com)"
echo "3. ✅ Render account (sign up at render.com)"
echo "4. ✅ OpenAI API key"
echo ""

echo "🔧 Configuration Files Created:"
echo "✅ I-TO-SAI-FE/vercel.json - Vercel configuration"
echo "✅ I-TO-SAI-BE/src/main/resources/application.yml - Spring Boot config"
echo "✅ I-TO-SAI-BE/render.yaml - Render configuration"
echo "✅ I-TO-SAI-FE/src/config/api.ts - Frontend API config"
echo "✅ DEPLOYMENT_GUIDE.md - Complete deployment guide"
echo ""

echo "📝 Next Steps:"
echo "1. Push your code to GitHub"
echo "2. Follow the DEPLOYMENT_GUIDE.md for step-by-step instructions"
echo "3. Deploy backend to Render first"
echo "4. Deploy frontend to Vercel second"
echo "5. Configure environment variables in both platforms"
echo ""

echo "🔑 Required Environment Variables:"
echo "Backend (Render):"
echo "  - JAVA_VERSION=24"
echo "  - OPENAI_API_KEY=your_openai_api_key"
echo "  - DATABASE_URL=postgresql://user:pass@host:port/db"
echo "  - DB_USERNAME=itosai_user"
echo "  - DB_PASSWORD=your_password"
echo ""
echo "Frontend (Vercel):"
echo "  - VITE_API_URL=https://your-backend-url.onrender.com"
echo ""

echo "📖 For detailed instructions, see DEPLOYMENT_GUIDE.md"
echo ""

echo "🎯 Quick Commands:"
echo "# Test locally first:"
echo "cd I-TO-SAI-BE && ./mvnw spring-boot:run"
echo "cd I-TO-SAI-FE && npm run dev"
echo ""
echo "# Check if everything is working:"
echo "curl http://localhost:8080/login"
echo "curl http://localhost:5173" 