version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: sss_db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER:     ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./I-TO-SAI-BE
      dockerfile: Dockerfile
    container_name: sss_backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL:      ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_APP_PASSWORD: ${MAIL_APP_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: TRACE
    depends_on:
      - db

  frontend:
    build:
      context: ./I-TO-SAI-FE
      dockerfile: Dockerfile
    container_name: sss_frontend
    restart: unless-stopped
    depends_on:
      - backend

    volumes:
      - /home/ubuntu/letsencrypt:/etc/letsencrypt:ro
      - /home/ubuntu/certbot:/var/www/certbot
      - ./I-TO-SAI-FE/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    ports:
      - "80:80"
      - "443:443"

volumes:
  db_data:

